#!/bin/bash
# SPDX-FileCopyrightText: 2025 Rehpotsirhc
#
# SPDX-License-Identifier: GPL-3.0-or-later

scriptpath="$(dirname $(readlink -f $0))"

if [[ -f "$scriptpath/target/release/dmenu_drun" ]]; then
    sudo cp "$scriptpath/target/release/dmenu_drun" /usr/bin/dmenu_drun
    sudo chmod +x /usr/bin/dmenu_drun
else
    echo "$scriptpath/target/release/dmenu_drun does not exist"
fi
